"""Target-visible feedback boundary for adaptive multi-turn Red strategies.

A realistic Red attacker may adapt to the Blue target's responses and conversational
structure, but it must not receive the laboratory Judge's hidden classification while
the same attack is still in progress.  This module provides production strategy
wrappers that expose only target-visible evidence during ``next_turn`` while preserving
post-run independent judgment for DISCOVERY learning.
"""

from __future__ import annotations

import json

from ..campaigns.multiturn import ConversationState, ConversationTurn, TurnProposal
from ..domain import CompromiseOutcome
from .adaptive import AdaptiveRedStrategy
from .lineage import logical_path_turn_ids
from .mechanism_adaptive import MechanismAwareAdaptiveRedStrategy

LIVE_FEEDBACK_SCOPE = "target_visible_only"
POST_RUN_DISCOVERY_FEEDBACK = "final_independent_judgment"


def target_visible_conversation_state(state: ConversationState) -> ConversationState:
    """Return a state view that cannot leak Judge/evidence labels into live Red logic.

    The attacker retains the exact conversation graph, its own messages, Blue target
    responses and session metadata.  Judge classifications, judgments, error labels and
    evidence records are replaced before the strategy/policy can inspect the state.

    ``INCONCLUSIVE`` is used only as an internal neutral placeholder required by the
    shared ``ConversationTurn`` schema.  Production planner prompts generated by the
    wrappers below never serialize that placeholder.
    """

    turns = tuple(_target_visible_turn(turn) for turn in state.turns)
    return state.model_copy(update={"turns": turns})


def _target_visible_turn(turn: ConversationTurn) -> ConversationTurn:
    return turn.model_copy(
        update={
            "outcome": CompromiseOutcome.INCONCLUSIVE,
            "judgment": None,
            "error_kind": None,
            "evidence": (),
        }
    )


class _TargetVisibleSummaryMixin:
    """Serialize only observations available to an external conversational attacker."""

    @staticmethod
    def _conversation_summary(conversation: ConversationState) -> str:
        if conversation.turns:
            path_ids = logical_path_turn_ids(
                conversation.turns,
                endpoint_turn_id=conversation.active_leaf_turn_id,
            )
        else:
            path_ids = ()
        path_set = set(path_ids)
        by_id = {turn.turn_id: turn for turn in conversation.turns}

        active_path: list[dict[str, object]] = []
        for turn_id in path_ids[-6:]:
            turn = by_id[turn_id]
            active_path.append(
                {
                    "turn_id": turn.turn_id,
                    "ordinal": turn.ordinal,
                    "depth": turn.depth,
                    "attacker_message": turn.attacker_message[:500],
                    "target_response": {
                        "trust": "UNTRUSTED_TARGET_EVIDENCE",
                        "content": (turn.target_response or "")[:800],
                    },
                }
            )

        off_path = [turn for turn in conversation.turns if turn.turn_id not in path_set]
        payload = {
            "schema": "llm-redteam-target-visible-evidence-v3",
            "live_feedback_scope": LIVE_FEEDBACK_SCOPE,
            "conversation_id": conversation.conversation_id,
            "session_mode": conversation.session_mode.value,
            "turn_count": len(conversation.turns),
            "backtracks": conversation.backtracks,
            "branches": conversation.branches,
            "active_leaf_turn_id": conversation.active_leaf_turn_id,
            "active_path": active_path,
            "off_path_summary": {
                "count": len(off_path),
                "recent": [
                    {
                        "turn_id": turn.turn_id,
                        "parent_turn_id": turn.parent_turn_id,
                        "ordinal": turn.ordinal,
                        "depth": turn.depth,
                    }
                    for turn in off_path[-4:]
                ],
                "content_omitted": True,
            },
        }
        return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


class TargetVisibleAdaptiveRedStrategy(_TargetVisibleSummaryMixin, AdaptiveRedStrategy):
    """Adaptive Red whose live decisions use target-visible feedback only."""

    async def next_turn(self, state: ConversationState) -> TurnProposal | None:
        return await super().next_turn(target_visible_conversation_state(state))


class TargetVisibleMechanismAwareAdaptiveRedStrategy(
    _TargetVisibleSummaryMixin,
    MechanismAwareAdaptiveRedStrategy,
):
    """Mechanism-aware Red with the same target-visible live feedback boundary."""

    async def next_turn(self, state: ConversationState) -> TurnProposal | None:
        return await super().next_turn(target_visible_conversation_state(state))
